--lect * from customer;

--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as total_revenue
from customer
group by gender 

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount
from customer 
where discount_applied = 'yes' and purchase_amount >= (Select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
 
 SELECT TOP 5
    Item_Purchased,
ROUND(AVG(Review_Rating), 2) AS Avg_Review_Rating
FROM customer
GROUP BY Item_Purchased
ORDER BY Avg_Review_Rating DESC;

 --Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type,
ROUND(AVG(Purchase_amount),2) as average_purchase_amount
from customer
where shipping_type in('standard','express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 

select subscription_status,
COUNT(customer_id) as Total_customer,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(Purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by Total_revenue,avg_spend DESC

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select TOP 5 item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END )/COUNT (*) ,2) AS discount_rate
from customer
group by item_purchased 
order by discount_rate DESC


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as(
select customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 THEN 'NEW'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END as customer_segment
from customer

)

select customer_segment,count(*) as "Number of Customer"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category

  select * from Customer

    with item_counts as(
    select category,
    item_purchased,
    COUNT (customer_id) as total_orders,
    Row_number() over(partition by category order by count(customer_id) DESC) as item_rank
    from customer
    group by category, item_purchased 
    )

    select item_rank,category,item_purchased,total_orders
    from item_counts
    where item_rank <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select Subscription_status ,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by Subscription_status

--Q10. What is the revenue contribution of each age group? 

select  * from customer

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue DESC


select @@SERVERNAME

select * from sys.databases

select * from sys.tables

use RAKESH_DB

select * from dbo.customer
select * from customer


SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'customer';






